### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by chanqun** [ksh9241/reservationProject#1]
.gitignore을 했는데 다른 파일들이 같이 올라왔네요

**Comment by chanqun** [comment]
WebMvcContextConfiguration.java 에서 		
resolver.setMaxUploadSize(200000000); size를 매직 변수로 뽑는 것도 좋습니다.
private int TEN_MEGA = 10 * 1024 * 1024;

**Comment by chanqun** [comment]
전체적으로 formatting이 안 되어 있네요
for(int i=0;i<comments.size();i++) {
			//List<CommentImage>있는거 db에서 가져온 후 맞는 comments list에 담기
			averageScore+=comments.get(i).getScore();
			List<CommentImage> commentImages = commentImageSvc.commentImgByCommentId(comments.get(i).getCommentId());
			if(commentImages!=null) {
				comments.get(i).setCommentImages(commentImages);
			}
		}

**Comment by chanqun** [comment]
Map<String,Object> map = new HashMap<>();
		map.put("displayInfo", displayInfo);
		map.put("productImages", productImages);
		map.put("displayInfoImage", displayInfoImage);
		map.put("comments", comments);
		map.put("averageScore", averageScore);
		map.put("productPrices", productPrices);
객체로 생성해서 관리하는 것이 좋지 않을까요?

category promotion product 전부 객체로 관리할 수 있을 것 같네요


public Map<String,Object> mainProductListById(@RequestParam int categoryId,@RequestParam int start){
		Map<String, Object> map = new HashMap<>();
		if(categoryId!=0) {

**Comment by chanqun** [comment]
fileId = reViewSvc.fileInfoInsert(fileMap);

insertFileInfo 라는 함수명이 더 적절할 것 같네요

**Comment by chanqun** [comment]
흠 클린코드
함수명, formatting, 매직넘버 등 전체적으로 다시 확인하시면 좋을 것 같네요
함수 하나에는 한 가지 기능

**Comment by ksh9241** [comment]
감사합니다 알려주신부분 수정해서 빠른시일내로 업로드하겠습니다 ㅎ

**Comment by chanqun** [comment]
세환씨 일을 할만하신가요 ㅎㅎ
